name: Publish

on:
  push:
    tags:
      - v*

  workflow_dispatch:

jobs:
  build:
    name: Publish Web Extension
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3.3.0
        with:
          node-version: 16.3.0

      - name: Build
        run: npm install && npm run-script build

      - name: Easy Zip Files
        uses: vimtor/action-zip@v1
        with:
          files: dist/
          dest: YoutubeClipPlaylist.zip
          # https://github.com/vimtor/action-zip/issues/8#issuecomment-917654348
          recursive: true

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: |
            YoutubeClipPlaylist.zip
            NOTICE
          retention-days: 10

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: artifact

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: NOTICE
          prerelease: true
          files: |
            YoutubeClipPlaylist.zip

      - name: Upload to Chrome Web Store
        uses: mnao305/chrome-extension-upload@2.2.0
        with:
          file-path: YoutubeClipPlaylist.zip
          extension-id: ${{ secrets.EXTENSION_ID }}
          client-id: ${{ secrets.CLIENT_ID }}
          refresh-token: ${{ secrets.REFRESH_TOKEN }}
