name: Upload

on:
  push:
    tags:
      - v*

  workflow_dispatch:

jobs:
  build:
    name: Build Extension
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3.3.0
        with:
          node-version: 16.3.0

      - name: Write tag version into manifest.json
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          npx json -I -f manifest.json -e "this.version='$(echo ${GITHUB_REF/refs\/tags\//} | sed 's/v//')'"
          npx json -I -f package.json -e "this.version='$(echo ${GITHUB_REF/refs\/tags\//} | sed 's/v//')'"

      - name: NPM install
        run: npm install

      - name: Build
        run: npm run-script build

      - name: Easy Zip Files
        uses: vimtor/action-zip@v1
        with:
          files: dist/
          dest: YoutubeClipPlaylist.zip
          # https://github.com/vimtor/action-zip/issues/8#issuecomment-917654348
          recursive: true

      - name: Build DEBUG
        run: npm run-script build:dev

      - name: Easy Zip Files
        uses: vimtor/action-zip@v1
        with:
          files: dist/
          dest: YoutubeClipPlaylist_DEBUG.zip
          # https://github.com/vimtor/action-zip/issues/8#issuecomment-917654348
          recursive: true

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: |
            YoutubeClipPlaylist.zip
            YoutubeClipPlaylist_DEBUG.zip
            NOTICE
          retention-days: 10

  upload_to_chrome_web_store:
    name: Upload to chrome web store
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: artifact

      - name: Upload to Chrome Web Store
        uses: mobilefirstllc/cws-publish@latest
        with:
          action: 'upload' # one of: upload, publish, testers
          client_id: ${{ secrets.CLIENT_ID }}
          client_secret: ${{ secrets.CLIENT_SECRET }}
          refresh_token: ${{ secrets.REFRESH_TOKEN }}
          extension_id: ${{ secrets.EXTENSION_ID }}
          zip_file: YoutubeClipPlaylist.zip
